### PR TITLE
feat: replace faker with custom fake data generator

### PR DESCRIPTION
**Pull request by angeloashmore**
## Types of changes

- [ ] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR replaces `faker` with a custom fake data generator.

Since this package was first written, `faker` has gone through [some controversy](https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected).

Rather than migrate to the refreshed community effort (`@faker-js/faker`), this is a good opportunity to shrink `@prismicio/mock` by replacing it with a smaller alternative.

## Checklist:

- [ ] My change requires an update to the official documentation.
- [ ] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [x] All new and existing tests are passing.

🧸

### CODE REVIEW

**Comment by lihbr** [comment]
Do you think we can take advantage of that to drop faker cache?

This way when we call a function twice with the same seed it gives you back the same result.

**Comment by angeloashmore** [comment]
> Do you think we can take advantage of that to drop faker cache?
> 
> This way when we call a function twice with the same seed it gives you back the same result.
> 
> Not providing a seed could just result in it being Math.random() or similar~

This should be possible. However, I think it could cause some usability issues. If you use `prismicM.model.richText()` more than once in a test, you would need to generate a unique seed for each one (or expect to get the same model each time).

For example, the following mock would produce a Group field with a Boolean field, both with the same label and placeholder text, if a specific seed always produced the same result:

```ts
prismicM.model.group({
	seed: "foo",
	fields: {
		boolean: prismicM.model.boolean({ seed: "foo" }),
	},
});
```

Creating unique seeds for each model call could be tedious.

Randomness is implemented through `seed-rand` in this new mock data generator, which will generate a reproducible sequence of numbers based on a seed. For a given seed and set of mock function calls, you will always get the same result in the same order. If you change the order of the function calls, however, you will get different results.

This seems like a decent trade-off. As long as you have a single non-changing value in a given context (e.g. a test name), you are guaranteed to get unique, reproducible values each time.

**Comment by lihbr** [comment]
OK then, I think my issue is more related with how I think of a seed here then, to me it's as-in Minecraft (yeah ;_;):
- When you generate a world you can input a seed;
- Creating two worlds with the same seed would end up creating the same world twice.

Which transposes here:
- When you generate a field you can input a seed;
- Creating two fields with the same seed would end up creating the same field twice (following the Minecraft logic I have).

Can we consider having a way to disable/enable the cache at least? Could be with a `cache` boolean, or another `cachedSeed` property (or `uncachedSeed` / `pureSeed` the other way around to not have a breaking change)

**Comment by angeloashmore** [comment]
We discussed this in a different thread, but I'll leave some notes here for the record:

This PR will be merged as is with an implicit state between mock calls with the same seed.

In a future PR, the following will be implemented:
- Remove the implicit state by changing all mock calls to always return the same value for a given seed.
- Create a new API to instantiate a stateful mock container. Mock values generated from the container will be unique for the given origin seed and order of calls. This will act like the current implementation, but without the need to pass the same seed for each call.

This library will eventually be replaced with a solution more integrated with the Prismic API. Stay tuned for more details. 👀

**Pull request merged**
